<body style="background-color: #f4f4f4; font-family: 'Arial', sans-serif;">

<H1 align='center' style="margin-top: 50px;">
    <font color='#34495e' size="8">
        GETTING STARTED WITH PYTHON
    </font>
</H1>

<H2 align='center' style="margin-top: 30px;">
    <font color='#5dade2' size="6">
        PREPARATORY SESSION
    </font>
</H2>

</body>

<H1 align='left'><font color='blue'><font size="">Session Agenda</font></H1>

<font size='4'>
<li> Printing Statements<br>
<li> Introduction to variables<br>

<li> Data Types: String, Integers and Float<br>
<li> Data Structures: List, Tuples and Dictionary<br>

<li>Bonus : Introduction to conditional statements: if,else<br>
<li>Bonus : Introduction to Loops: for loop<br>

<H1 align='left'><font color='Blue'><font size="">Introduction</font></H1>

<font size="4">Automobiles are moving towards global production networks. With variability in automobile models, there is a lot of uncertainty in the demand. It requires better visibility towards car performance for investments as well as operation and to avoid the risk of inventory stock-outs.<br>
<br>
Cars Sons Ltd. is an automobile company incorportated on February, 1996. The company  offers a full range of cars from entry-level to stylish Hatchback along with Sedans, SUVs and MUVs. The company is engaged in the business of manufacturing, purchase and sale of motor vehicles and spare parts (automobiles).<br>
<br>
The company has booked a turnover of around $12.5mn last year. The company is looking forward to expanding its range of products and services and will introduce new types of the automobile in the market.<br>
<br>
You have been hired as a Data Scientist in Cars Sons Ltd. The data for the company products have been provided and are required to create structured data which includes the various attributes of the product along with the sales figures.
</font>

## Introduction to Google Colab

Welcome to Google Colab! ðŸš€

Google Colab is an interactive environment that lets you write and execute Python code in the browser. It's just like a notebook, but digital.

Here you'll find two main types of cells:
1. **Text Cells** (like this one) - where you can write explanations, notes, or even add images.
2. **Code Cells** - where you'll write and execute Python code.

Let's get started with the basics!

### Printing Messages in Code

When we say "print" in coding, we don't mean "print out on paper" like a printer would do. Instead, we mean "display on the screen."

In our digital notebook here (Google Colab), when we ask the computer to `print` something, it will show the message directly below the code we ran. This is a way for the computer to talk back to us or show us some result.

Think of it as if you're asking the computer to write down an answer for you in this notebook. So, when you see the word `print` in the code, just think "display on the screen" and not "print on paper".

### Running Our Code

To "run" or "execute" our code, we follow these steps:

1. Click on the cell (a box that contains our code).
2. Look for a play button on the left side of the cell.
3. Click the play button to run the code!

Try it now with the cell above that says `print("Hello, world!")`.

In [9]:
print("Hello, world! This is Amish") # shift + enter

Hello, world! This is Amish

When you run the cell above, the computer will display the message "Hello, world!".

### Talking to Ourselves (and Others!)

In coding, we often leave little notes for ourselves or for others to explain what we're doing. These notes are called "comments".

Comments are NOT run as code. They're just for humans to read.

In [10]:
# This is a comment. The computer will ignore it.
print("This is code. The computer will run it!")

This is code. The computer will run it!

### Everyone Makes Mistakes

Coding is about trying, making mistakes, and fixing them. If you make a mistake, the computer will show an "error" message. Don't be scared! It's just the computer's way of saying, "I'm confused."

Let's see what this looks like.

In [12]:
print(Hello, world!)

SyntaxError: invalid syntax (<ipython-input-12-d14e6f3d0ea2>, line 1)

Oops! We forgot to put our message in quotes. The computer is confused. Let's fix it by adding quotes around "Hello, world!".

# <font color='Blue'>Print Statements

<font color='blue'>*To start with, let's print some details of the company*

In [14]:
# Code cell
# This statement will print out the name of the company
print('The name of the company is Cars Sons Ltd.') # This is a print statement

The name of the company is Cars Sons Ltd.

**The print() function prints the specified message to the screen or other standard output device.**

# <font color='Blue'> Datatypes

In Python, and most programming languages, data types are a way of categorizing information. You can think of data types as labels for the kind of data you're dealing with. Python has several built-in data types, including:

**Integer**: These are whole numbers without a decimal point, such as 7, -3, 0, and 4567.

**Float**: These are numbers with a decimal point, such as 7.3, -0.7, or 0.0.

**String**: This is text data. In Python, you create a string by putting text inside single quotes ('hello') or double quotes ("hello").

**Boolean**: This data type has only two possible values: True or False. It's often used in conditions and comparisons.

In [15]:
# The print statement in python prints anything within the double quotes or single quotes as a string
print("Anything here such as words, symbols !@#$%^, integers 12345+2, floats 1.2, 2.3, 3.4 are all treated as a string")

Anything here such as words, symbols !@#$%^, integers 12345+2, floats 1.2, 2.3, 3.4 are all treated as a string

In [20]:
# To pring integers as just integers and not string, we print without the quotes
print(2)

2+2

### Why Use Commas in Print Statements?

When we're using the `print` function in Python, we have the ability to display multiple pieces of information together by separating them with commas. The comma does two things:

1. **Separation**: It allows us to list multiple items, whether they are strings, numbers, or other data types, that we want to display.
   
2. **Automatic Spacing**: The comma automatically adds a space between the items for us, making the output look neat without us manually adding spaces.

Let's see this in action.

Imagine we want to print the message about when a company was established. We have a sentence, a year the company started, a hyphen, and the current year. These are all separate pieces of information.

By using commas, we can easily list them in the `print` function:

In [30]:
print("The year the company was established is ",1996,"-", 2023, sep='')

The year the company was established is 1996-2023

In [31]:
print("The year the company was established is 1996-2023")

The year the company was established is 1996-2023

In [32]:
print('Total turnover of the company this year in Million $ is', 12.5)

Total turnover of the company this year in Million $ is 12.5

### <font color='Blue'> *Your turn to code!* </font>

 **Since these values are not stored, they cannot be used in future. Therefore, we need to store them in some objects, which are known as *variables*.**

# <font color='Blue'>Variables

<font color='blue'>*Let's create a variable and store the name of the company in it.*

In [47]:
company_name = "Cars and Sons Ltd" # variable is assigned and a value is stored in the variable

In [48]:
print('The name of the company is', company_name)

The name of the company is Cars and Sons Ltd

**Variables are containers for storing any data values. A variable is created the moment you first assign a value to it.**
* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _)
* Variable names are case-sensitive (age, Age and AGE are three different variables)

<font color='blue'>*Similarly we can store the year the company established in another variable*

In [49]:
year_started = 1996
print('The year the company established is', year_started)

The year the company established is 1996

# <font color='Blue'> Basic Operators

**Python provides various operators for performing different types of calculation on variables and values.<br> Below are some of the operators which are commonly used in python operations:**

|Operator|Symbol in Python|Description|
|---|---|---|
|Addition| +|Adds values on either side of the operator|
|Subtraction|-|Subtracts right hand operand from left hand operand|
| Multiplication| *|Multiplies values on either side of the operator
| Division| /|Divides left hand operand by right hand operand

In [50]:
# Adding two numbers
print(2+2)

4

In [51]:
# Subtracting two numbers
print(2-2)

0

In [52]:
# Multiplying two numbers
print(3*3)

9

<font color='blue'>*Sales team has provided you with the details of the cars including the prices of each type of car.They have received an order of 10 Sedan cars and they need to evaluate total sales for this order.<br>To perform this, we can use Basic Arithmetic operators in Python*

**Python allows you to perform various operation on variables and values. You can also manipulate the values present in the variables**

In [53]:
# Suppose the price of one sedan car is $30k
price_sedan = 30000 # variable to store the price of one Sedan car
print('Price of 1 Sedan Cars is $',price_sedan)

Price of 1 Sedan Cars is $ 30000

In [54]:
price_updated = price_sedan + price_sedan # By using Addition operator we have calculated the price of 2 sedan cars
print('Price of 2 Sedan Cars is $',price_updated)

Price of 2 Sedan Cars is $ 60000

**Let's get our hands dirty on some operators...**

Let's begin by finding the price of 12 sedan cars

In [55]:
price_final = price_sedan * 12
print('Price of 12 Sedan Cars is $',price_final)

Price of 12 Sedan Cars is $ 360000

**Let's try to combine multiple operators...**

<font color='blue'>*One of the most critical indicators automotive businesses need to be aware of is downtime. You have been provided with some details from the production department about the downtime hours for last month. To prepare a report you need to include the Average Downtime for the last month.*

*Average Downtime = (downtime hours in a time period) Ã· (total time available to produce vehicles in the same time period) x 100*

In [62]:
downtime_hours = 37
total_time = 240

average_downtime = (downtime_hours/total_time) * 100
print(f"The average downtime in hours is {round(average_downtime,2)}")

The average downtime in hours is 15.42

In [61]:
round(3.141592653)

3

### <font color='Blue'> *Your turn to code!* </font>

<font color='blue'>The safety of the workers in any business is always an issue of utmost importance, but in the automotive industry, safety incidents are a common issue that must continually be measured carefully to move toward a safer workplace.<br>Therefore, the Safety officer has provided you with the data related to the safety incidents and you need to calculate the percentage of safety incidents

Safety incidents per employee = (number of safety incidents in a time period) Ã· (number of employees working during the time period)  x 100

In [63]:
#Calculate safety incidents per employee
safety_incidents = 44 #Number of safety incidents in a time period
total_employees = 1568 #Number of employees working during the time period

# Write a print statement : "The percentage of safety incidents is _%"
percentage_of_safety_incidents = (safety_incidents/total_employees) * 100
# Write a print statement : "The percentage of safety incidents is _%"
print(f'The percentage of safety incidents is {round(percentage_of_safety_incidents, 2)}%')

The percentage of safety incidents is 2.81%

In [66]:
safety_incidents = 44
total_employees = 1568

incidents_per_employee= round(safety_incidents / total_employees * 100, 2)

print("The percentage of safety incidents is ", incidents_per_employee, "%", sep="")

The percentage of safety incidents is 2.81%

In [67]:
print(f"The porcentage of safety incidents is {round((safety_incidents/total_employees * 100),2)}%")

The porcentage of safety incidents is 2.81%

In [70]:
print(f"The percentage of safety incidents is {round (44/1568, 2)*100}%")

The percentage of safety incidents is 3.0%

In [71]:
Percentage=(safety_incidents/total_employees)*100

print(f"The percentage of safety incidents is {Percentage}%")

The percentage of safety incidents is 2.806122448979592%

In [75]:
safety_incident=44
total_employees=1568

print(f"The percentage of safety incidents is {round(safety_incident/total_employees *100,2)} %")

The percentage of safety incidents is 2.81 %

In [81]:
print(f"The percentage of safety incidents is {round (44/1586 * 100, 2)}%")

The percentage of safety incidents is 2.77%

# <font color='Blue'> Data Structures

<font color='blue'>*The Marketing team has given you the type of products the company is manufacturing. To keep things in order, let's store all the data in a variable.<br> Since we already know how to store values in a variable, let's start by storing the type of cars manufactured.*

In [ ]:
car_type_1 = 'Sedan'
car_type_2 = 'Hatchback'
car_type_3 = 'SUV'
car_type_4 = 'MUV'

<font color='blue'>*But storing each value in a different variable will be a very lengthy process in case the data is huge. Therefore, we need a way to store multiple values in a single variable.*

<font color='blue'>For this, **list** data structure can be used.

## <font color='Blue'>List

In [82]:
cars_type = ["Sedan", "Hatchback", "SUV", "MUV"]
print(cars_type)

['Sedan', 'Hatchback', 'SUV', 'MUV']

In [83]:
print(cars_type)

['Sedan', 'Hatchback', 'SUV', 'MUV']

In [84]:
cars_type[2]

'SUV'

In [85]:
cars_type.append("HUV")

In [86]:
cars_type

['Sedan', 'Hatchback', 'SUV', 'MUV', 'HUV']

In [87]:
cars_type.remove("SUV")
print(cars_type)

['Sedan', 'Hatchback', 'MUV', 'HUV']

A list in Python is an ordered group of items or elements, and these list elements don't have
to be of the same type. Python Lists are mutable objects that can change their values.<br>
<br>A list contains items separated by commas and enclosed within square brackets.
List indices, like strings, start at 0 at the beginning of the list

<font color='blue'>*All types of cars are now being stored in a single variable. Similarly, we can do the same process for other attributes as well.*

In [88]:
mileage = [15, 19, 12, 10]
print('Mileage:',mileage)

Mileage: [15, 19, 12, 10]

In [89]:
# Create a list that contains the values for sales that happened to date. The values are 200, 652, 412, 123 for "Sedan", "Hatchback", "SUV", "MUV" respectively
# print those values as well
sales_to_date=[200,652,412,123]

In [ ]:
print(mileage[0])
print(sales_to_date[0])
print(cars_type[0])


**You can also do modifications and access the elements in the list as lists are mutable.**

<font color='blue'>*Due to the less demand for MUV cars in the market, the company has decided to stop the production of these types of cars and instead introduce a new type in the market. <br>As per the reports received from the Marketing team, the data shows that demand for Hybrid cars is high among a significant amount of population and hence, company has decided to launch its new Hybrid car in the market this month.*

In [90]:
cars_type = ['Sedan', 'Hatchback', 'SUV', 'MUV']

In [91]:
print(cars_type)

['Sedan', 'Hatchback', 'SUV', 'MUV']

In [92]:
cars_type.remove("MUV") # remove() method removes the first matching element from the list, value 'MUV' is removed from the variables cars_type

print('Cars:',cars_type)

Cars: ['Sedan', 'Hatchback', 'SUV']

In [93]:
cars_type.append("Hybrid_car") # append() method in python adds a single item to the existing list, it adds the new type Hybrid_car to the list variable cars_type

print('Cars:',cars_type)

Cars: ['Sedan', 'Hatchback', 'SUV', 'Hybrid_car']

In [ ]:
cars_type = ["Sedan", "Hatchback", "SUV", "MUV"]
print(cars_type)

<font color='blue'>*You still have the data associated with the MUV type of cars and new data for the Hybrid car. So instead of deleting the previous data and adding the new data, you can also replace it with new data from Hybrid car. Therefore instead of using the remove and append function, you can also modify the elements by accessing the index values.*

In [94]:
mileage

[15, 19, 12, 10]

In [95]:
mileage[3]

10

In [96]:
mileage[3] = 9 # modifying the mileage data [replacing 3rd index position i.e. 10 with a new value 9]
print('Mileage:',mileage)

Mileage: [15, 19, 12, 9]

<font color='blue'>*Instead of getting a single element, you can also get a section of list by slicing the list*

In [97]:
cars_type

['Sedan', 'Hatchback', 'SUV', 'Hybrid_car']

In [99]:
cars_type

['Sedan', 'Hatchback', 'SUV', 'Hybrid_car']

In [100]:
cars_type[0:2] # will return the first two elements of cars_type which are indexed as 0 and 1.
              #NOTE- [a:b], this will take elements from 'a' to 'b-1'

['Sedan', 'Hatchback']

### <font color='Blue'> *Your turn to code!* </font>

In [ ]:
# print the numbers 19,12 from the mileage list using list slicing
mileage = [15,19,12,9]

## <font color='Blue'> Dictionary

Dictionaries are incredibly useful data structures in Python. Think of them as real-life dictionaries: you have a word (the "key") and a definition (the "value").

In Python, dictionaries are a collection of key-value pairs. They're unordered, changeable, and do not allow duplicates - which means that each key must be unique. You can use any immutable data type as a key (like numbers or strings), and practically any data type as a value.

Here's an example of a dictionary:

```python
person = {
    "name": "Alice",
    "age": 25,
    "city": "New York"
}
```

In this dictionary, "name", "age", and "city" are the keys, and "Alice", 25, and "New York" are the corresponding values.

You can access the values in a dictionary by referring to the name of the key like this:

```python
print(person["name"])  # Will output: Alice
```

If you want to change a value in the dictionary, you can do so by referencing the key:

```python
person["age"] = 26  # Alice just had a birthday!
```

If you want to add a new key-value pair, you can do so like this:

```python
person["job"] = "Engineer"  # Alice is an Engineer
```

You can also remove key-value pairs using the `del` keyword:

```python
del person["city"]  # Alice doesn't want to share her city anymore
```

Dictionaries can also hold complex types like lists, tuples, and other dictionaries. This makes them really powerful for structuring and organizing data in your Python programs.

<font color='blue'>*So the above data we have stored in a List or Tuple for each type of car is not linked directly with the type of car. To link data with each other Dictionaries are used.<br>Let's create a dictionary to store the sales figures of last month based on car types in a key: value format*

In [109]:
sales_last_month = {'Sedan': 200000,
                    'Hatchback':300000,
                    'SUV':150000,
                    'Hybrid_car':0}

print('Sales last month:',sales_last_month)

Sales last month: {'Sedan': 200000, 'Hatchback': 300000, 'SUV': 150000, 'Hybrid_car': 0}

In [110]:
sales_last_month.keys()

dict_keys(['Sedan', 'Hatchback', 'SUV', 'Hybrid_car'])

In [111]:
sales_last_month.values()

dict_values([200000, 300000, 150000, 0])

In [112]:
print(sales_last_month['SUV'])

150000

**A dictionary is a collection that is unordered, mutable, and indexed. They have keys and values.**<br>
* Each key is separated from its value by a colon (:), the items are separated by commas, and the whole thing is enclosed in curly braces<br>
* Keys are unique within a dictionary while values may not be
* The values of a dictionary can be of any type

**Like Lists, you can also do the modification in Dictionaries as well, for example Slicing, Updating and Adding new values**

<font color='blue'>*Just now you received a notification that the first model of Hybrid car has been sold last month.<br>
So you decide to change it in your dictionary data accordingly*

In [113]:
sales_last_month

{'Sedan': 200000, 'Hatchback': 300000, 'SUV': 150000, 'Hybrid_car': 0}

In [114]:
sales_last_month['Hybrid_car'] = 20000

In [115]:
sales_last_month

{'Sedan': 200000, 'Hatchback': 300000, 'SUV': 150000, 'Hybrid_car': 20000}

# Bonus Material (Advanced Python)

# <font color='Blue'>Comparison Operators

**Comparison operators are used for comparing the values. It either returns True or False according to the condition.**

|Operator|Symbol in Python|Description|
|---|---|---|
|Equals| ==|If the values of two operands are equal, then the condition becomes true.|
|Not Equal to|!=|If values of two operands are not equal, then condition becomes true.
| Greater than| >|If the value of left operand is greater than the value of right operand, then condition becomes true.
| Less than| <|If the value of left operand is less than the value of right operand, then condition becomes true.
|Greater than or Equal to|>=|If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.
|Less than or Equal to|<=|If the value of left operand is less than or equal to the value of right operand, then condition becomes true.

In [123]:
print(1<=1)

True

<font color='blue'>*To prepare monthly report, Marketing team has requested to know if sales of Sedans are higher than Hybrid car so that they can decide which type of car to promote more and optimize their marketing costs accordingly.<br>Let's compare the sales from last month for different car types.*

In [124]:
sales_last_month['Sedan']

200000

In [125]:
sales_last_month['Hybrid_car']

20000

In [126]:
sales_last_month['Sedan'] > sales_last_month['Hybrid_car']

True

<font color='blue'>*This shows that sales of Sedans are higher than sales of Hybrid car for last month.*

**If the condition applied is valid, then it will result as *'True'* output, otherwise will return *'False'* as an output.<br>Below are some common operators used in Python:**

In [127]:
sales_last_month['Hatchback']

300000

In [128]:
sales_last_month['Hatchback'] > sales_last_month['Hybrid_car']

True

# <font color='Blue'>Conditional Statements

**Conditional Statement in Python perform different actions depending on whether a specific condition evaluates to true or false.<br>if-else are the conditional statements**

## <font color='Blue'> if-else



## Understanding `if-else` Statements in Python

### What is an `if-else` statement?

At its core, an `if-else` statement is like making a decision. It's like asking: "Is it raining outside?" If the answer is yes, you might decide to carry an umbrella. If the answer is no, you might choose to wear sunglasses.

In Python, we use the `if-else` structure to make decisions in our code based on certain conditions.

### Basic Structure:

Here's what the structure looks like:

```python
if condition:
    # Do something if the condition is True
else:
    # Do something else if the condition is False
```

### A Simple Example:

Imagine you have a variable `weather` which can be either `"sunny"` or `"rainy"`. Here's how you could use an `if-else` statement:

```python
weather = "sunny"

if weather == "rainy":
    print("I will carry an umbrella!")
else:
    print("I will wear sunglasses!")
```

In this example, since `weather` is `"sunny"`, the output will be:

```
I will wear sunglasses!
```

<font color='blue'>*You have been given the data of car ratings from the customers. Based on this you need to write a program that gives car performance on inputting the car name.*

In [130]:
# stored the ratings of each car in a dictionary
cars_ratings= {
      'Sedan_1'    : 64,
      'Sedan_2'    : 49,
      'Hatchback_1': 59,
      'Hatchback_2': 78,
      'SUV_1': 32,
      'SUV_2': 84,
      'MUV_1': 21,
      'MUV_2': 31
}
print('Ratings of each car:', cars_ratings)

Ratings of each car: {'Sedan_1': 64, 'Sedan_2': 49, 'Hatchback_1': 59, 'Hatchback_2': 78, 'SUV_1': 32, 'SUV_2': 84, 'MUV_1': 21, 'MUV_2': 31}

In [131]:
cars_ratings['Sedan_1']

64

In [ ]:
cars_ratings

In [ ]:
cars_ratings

In [ ]:
cars_ratings.keys()

In [132]:
if cars_ratings['MUV_2'] > 50:
  print('MUV_2 this car is efficient')
else:
  print("this car is inefficient")

this car is inefficient

In [133]:
# a car is said to be well-performing if it's rating is greater than 50
# check whether Sedan_1 is a good performer

if (cars_ratings['Sedan_1']<50): # checking if it's lower than 50
  print("Sedan_1 is not performing well")
else:
  print("Sedan_1 performs well")

Sedan_1 performs well

**Python if Statement is used for decision-making operations. It contains a body of code which runs only when the condition given in the if statement is true. If the condition is false, then the optional else statement runs which contains some code for the else condition.**

# <font color='Blue'>Loops

## <font color='Blue'> "for" Loop

Think of a `for` loop as a tool that lets you repeat a task over and over again, automatically. It's kind of like saying, "for each item in this group, do this task."

Let's consider an example of a shopping list.

Imagine you have a shopping list with some items you need to buy:

```python
shopping_list = ['milk', 'bread', 'eggs', 'butter']
```

You can use a `for` loop to go through each item in the list and print it out:

```python
for item in shopping_list:
    print(item)
```

This piece of code is essentially saying, "For each `item` in `shopping_list`, print the `item`."

When you run this code, Python looks at the first item in `shopping_list`, calls it `item`, and then does whatever you've told it to do in the body of the loop (in this case, `print(item)`). Python repeats this process for every item in the list. The output would be:

```
milk
bread
eggs
butter
```

Each loop through the list is called an iteration, and in every iteration, the variable `item` changes to the next item in the list.

You can also use `for` loops with a sequence of numbers using the `range()` function. For example, if you want to print the numbers 0 through 4, you can write:

```python
for i in range(5):
    print(i)
```

Here, `i` is a common variable name to use in such loops, and `range(5)` generates a sequence of numbers from 0 up to, but not including, 5. So, this loop will print out:

```
0
1
2
3
4
```

So, to put it simply, a `for` loop in Python lets you perform an action for each item in a list, or each number in a sequence. It's a super useful tool in programming that helps you automate repetitive tasks!

<font color='blue'>*Now in case we need to check for each type of car, we need to write the above code which will become very lengthy in case we have a huge amount of data. Hence, a loop can be used in that situation.*

In [134]:
cars_ratings

{'Sedan_1': 64,
 'Sedan_2': 49,
 'Hatchback_1': 59,
 'Hatchback_2': 78,
 'SUV_1': 32,
 'SUV_2': 84,
 'MUV_1': 21,
 'MUV_2': 31}

In [135]:
cars_ratings.keys()

dict_keys(['Sedan_1', 'Sedan_2', 'Hatchback_1', 'Hatchback_2', 'SUV_1', 'SUV_2', 'MUV_1', 'MUV_2'])

In [136]:
car_names= cars_ratings.keys()
# print all car names
for c in car_names:
  print(c)

Sedan_1
Sedan_2
Hatchback_1
Hatchback_2
SUV_1
SUV_2
MUV_1
MUV_2

In [ ]:
cars_ratings

In [ ]:
for key,value in cars_ratings.items():
  if value > 50:
    print(key, "is performing well")

**The *for* loop in Python is used to iterate over a sequence (list, tuple, string) or other iterable objects.
<br><br>Loop continues until we reach the last item in the sequence. The body of for loop is separated
from the rest of the code using indentation.**

#<font color='Blue'>Summary

<font size='4'>
<li> Understand how to create variables,store data in a variable and check the data types<br>
<li> Performed basic Arithmetic operations and storing data in List, Dictionaries<br>
<li> Performed basic comparison of variables by using different operators<br>
<li>Creating conditional statements by passing single conditions as well as multiple conditions.<br>
<li>Understand how to execute a similar condition multiple times by creating loops <br>
</font>

# <font color='blue'>Happy Learning !